config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size
  before_save {self.bleepify}

  def bleepify
    bleep = '$%@#-ing'
    min_bleep_size = bleep.length + 1
    words = self.content.split
    word_count = words.length
    char_count = self.content.length
    # one long word with no char space for bleep
    if word_count == 1 && char_count > (140-min_bleep_size)
      words = words
    # 1 word with char space to add bleep
    elsif word_count == 1 && char_count < (140-min_bleep_size)
      words = words.insert(0, bleep)
    # words with char space to add bleep
    elsif char_count< (140-min_bleep_size)
      bleep_index = rand(0..word_count)
      words = words.insert(bleep_index, bleep)
    # all other cases: replace word with bleep
    else
      bleep_index = rand(0..word_count)
      words[bleep_index] = bleep
    end
    self.content = words.join(' ')
  end

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

before_action :logged_in_user, only: [:create, :destroy]
before_action :correct_user, only: [:destroy]

def create
  @micropost = current_user.microposts.build(micropost_params)
  if @micropost.save
    flash[:success] = "Bleep $%@#-ing created!"
    redirect_to root_url
  else
    @feed_items = []
    render 'static_pages/home'
  end
end

def destroy
  @micropost.destroy
  flash[:success] = "Bleep $%@#-ing deleted"
  redirect_to request.referrer || root_url
end

private

  def micropost_params
    params.require(:micropost).permit(:content, :picture)
  end

  def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # returns the full title on per-page basis
  def full_title(page_title = '')
    base_title = "Bleeper"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://ramon-luis-bleeper.herokuapp.com/">Bleeper</a> - A $%@#-ing Twitter clone
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to("Bleeper", root_path , id: "logo") %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("Home", root_path) %></li>
        <li><%= link_to("Help", help_path) %></li>

        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new bleep..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "bleep") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  Bleeper is a Twitter clone that adds random $%@#-ing bleeps to user posts.  Post your favorite thoughts and bleeper will auto-magically make them even $%@#-ing better.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Please don't contact us.  We don't $%@#-ing care.
</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  It's a Twitter clone. Go to <a href="http://www.twitter.com">Twitter</a> for the real thing.
</p>

app/views/static_pages/home.html.erb
<div class="homepage">
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Your $%@#-ing Bleeper Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <%= link_to image_tag("bleeper_logo.png", alt: "Bleeper logo"), 'http://ramon-luis-bleeper.herokuapp.com' %>
    <h1>Bleeper</h1>
    <h2>A $%@#-ing Twitter Clone</h2>
    <p>Bleeper is a Twitter clone that adds random $%@#-ing bleeps to user posts.  Post your favorite thoughts and bleeper will auto-magically make them even $%@#-ing better.
    </p>
    <%= link_to("Sign up now!", signup_path , class: "btn btn-lg btn-primary") %>
  </div>
  <% end %>
</div>